Tabellen in supabase definieren!
create table public.deckel (
  id bigint generated by default as identity not null,
  "kundenId" bigint null,
  "getränkId" bigint null,
  anzahl numeric null,
  constraint deckel_pkey primary key (id)
) TABLESPACE pg_default;

create table public.getränke (
  id bigint generated always as identity not null,
  bezeichnung text null,
  preis double precision null,
  constraint getränke_pkey primary key (id)
) TABLESPACE pg_default;

create table public.kunden (
  id bigint generated always as identity not null,
  name text null,
  vorname text null,
  geburtstag text null,
  constraint kunden_pkey primary key (id)
) TABLESPACE pg_default;